# Generated by Django 3.2.8 on 2022-12-02 10:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=10)),
                ('whatsapp_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FlatTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('interested_in', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=256, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('attended_lead_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attended_lead_manager', to=settings.AUTH_USER_MODEL)),
                ('lead_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileNumberPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='91', max_length=256)),
                ('country_abbr', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinCodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TalukaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=250)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.buildingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=256)),
                ('market_value', models.BigIntegerField(blank=True, null=True, verbose_name='Market Value')),
                ('admin_rate', models.BigIntegerField(blank=True, null=True, verbose_name='Admin Rate')),
                ('amenities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.projectamenities')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSiteVisitDetailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('visited_on', models.DateTimeField(default=datetime.datetime)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.leadmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LeadMobileNumberMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.leadmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAddressMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.citymaster')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.countrymaster')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.districtmaster')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.leadmaster')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.pincodemaster')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.statemaster')),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.talukamaster')),
            ],
        ),
        migrations.CreateModel(
            name='FlatMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=250)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.wingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.channelpartnerowner')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerAddressMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField()),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.channelpartnermaster')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.citymaster')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.countrymaster')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.districtmaster')),
                ('pincode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.pincodemaster')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.statemaster')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.talukamaster')),
            ],
        ),
        migrations.AddField(
            model_name='buildingmaster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.projectmaster'),
        ),
    ]
