# Generated by Django 3.2.8 on 2022-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20221202_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
