# Generated by Django 3.2.8 on 2022-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_leadmaster_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='interested_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
